[package]
name = "hugr"
version = "0.1.0"
edition = "2024"

[dependencies]
libsql = "0.9.30"
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros"] }
tree-sitter = "0.26.10"
tree-sitter-go = "0.25.0"
tree-sitter-java = "0.23.5"
tree-sitter-python = "0.25.0"
tree-sitter-rust = "0.24.2"
tree-sitter-swift = "0.7.3"
tree-sitter-typescript = "0.23.2"
